version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8036:8080
volumes:
  mysql_volume:
